jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  # API Token configuration
  apiToken:
    tokenGenerationOnCreation: true

  # Tool configurations
  tool:
    git:
      installations:
        - name: "DefaultGit"
          home: /usr/bin/git
    maven:
      installations:
        - name: "Maven3"
          home: /opt/maven
          properties:
            - installSource:
                installers:
                  - maven:
                      id: "maven3"
                      version: "3.8.1"
    gradle:
      installations:
        - name: "Gradle6"
          home: /opt/gradle
          properties:
            - installSource:
                installers:
                  - gradle:
                      id: "gradle6"
                      version: "6.8.3"

# Credentials configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Docker Hub credentials"
          - usernamePassword:
              id: git_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Git credentials"
