jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin


  # Tool configurations
  tool:
    git:
      installations:
        - name: "DefaultGit"
          githome: /usr/bin/git


# Credentials section can be defined separately if needed
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: ratneshpuskar@gmail.com
              password: Premkumar@2
              scope: SYSTEM
              description: "Docker Hub credentials"

