jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin


  # Tool configurations
  tool:
    git:
      installations:
        - name: "DefaultGit"
          home: "/usr/bin/git"


  # Plugin installations
  plugins:
    - id: workflow-aggregator
      version: latest
    - id: git
      version: latest
    - id: maven-plugin
      version: latest
    - id: docker-plugin
      version: latest
    - id: credentials
      version: latest

# Credentials section can be defined separately if needed
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: ratneshpuskar@gmail.com
              password: Premkumar@2
              scope: SYSTEM
              description: "Docker Hub credentials"

