jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

tool:
  git:
    installations:
      - name: git
        home: /usr/bin/git

# Credentials configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Docker Hub credentials"
