jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins\n\n"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin@123

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              username: ratneshpuskar@gmail.com
              password: Premkumar@2
              scope: SYSTEM
              description: Credentials for git
