jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  # API Token configuration
  apiToken:
    tokenGenerationOnCreation: true

# Credentials configuration
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Docker Hub credentials"
          - usernamePassword:
              id: git_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Git credentials"
