jenkins:
  systemMessage: "Jenkins configured automatically"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  mode: NORMAL

  # Security and user setup
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
          apiToken: "your_generated_api_token_here"

  # Tool configurations
  tool:
    git:
      installations:
        - name: "DefaultGit"
          home: /usr/bin/git
    maven:
      installations:
        - name: "Maven 3.6.3"
          home: /usr/share/maven
    gradle:
      installations:
        - name: "Gradle 6.7"
          home: /usr/share/gradle

# Credentials section
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Docker Hub credentials"
          - usernamePassword:
              id: git_credentials
              username: "ratneshpuskar"
              password: "Premkumar@2"
              scope: SYSTEM
              description: "Git credentials"
